---
# To get a hash on RHEL 6:
# python -c 'import crypt,getpass; print crypt.crypt(getpass.getpass())'
- hosts: passchange 
  become: yes
  gather_facts: no
  vars_prompt:
    - name: "username"
      prompt: "Enter username for changing password"
      private: no

  tasks:
  - name: Generate sha512 hash for new password.
    command: python -c 'import crypt,getpass; print crypt.crypt(getpass.getpass())'
    delegate_to: 127.0.0.1
    register: out

  - name: Update local user password.
    user:
      name: "{{ username }}"
      password: "{{ out.stdout }}"
      update_password: always
  
