---
- name: Remove old packages from /var/spool/repackage/
  hosts: repackage 
  sudo: yes
  remote_user: ansible
  tasks:
  - name: clean repackage dir
    command: 'find /var/spool/repackage/ -mtime +30 -exec rm {} \;'
