---
- name: CRR Failover Operations
  hosts: crr 
  user: ansible
  sudo: yes
  gather_facts: no
  vars:
    FS1: /app/ercot/crr/MIS
    FS2: /app/ercot/crr/CRROwnership
  tasks:
  - name: Nuke any processes left behind
    command: /sbin/fuser -ck {{ FS1 }} {{ FS2 }}
    tags:
      - nuke
    
  - name: Unmount target file system
    command: /bin/umount {{ FS1 }} {{ FS2 }}
    tags:
      - umount

  - name: Mount target file system
    command: /bin/mount -a 
    tags:
      - mount
