---
- name: Install 32-bit libraries for MMS LDAP installation.
  hosts: mms_ldap
  gather_facts: no
  sudo: yes

  tasks:
    - name: Install 32-bit glibc.
      yum: name=glibc.i686 state=present

    - name: Install 32-bit libstdc++.
      yum: name=libstdc++.i686 state=present

    - name: Install 32-bit zlib.
      yum: name=zlib.i686 state=present
