apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    ercot.com/product: "jenkins"
    ercot.com/jenkins-agent: "helm"
    ercot.com/helm-version: "3.4.2"
spec:
  containers:
  - name: "jnlp"
    image: "docker.repo.ercot.com/ercot/jenkins/agent/inbound:latest"
    imagePullPolicy: "Always"
    tty: false
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m
  - name: "helm"
    image: "docker.repo.ercot.com/ercot/tools/openshift/client/helm:latest"
    imagePullPolicy: "Always"
    tty: true
    securityContext:
      runAsUser: "1000"
      runAsGroup: "1000"
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m