apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    ercot.com/product: "jenkins"
    ercot.com/jenkins-agent: "container"
spec:
  volumes:
    - name: "buildah-cache"
      emptyDir:
        medium: "Memory"
  containers:
  - name: "jnlp"
    image: "docker.repo.ercot.com/ercot/jenkins/agent/inbound:latest"
    imagePullPolicy: "Always"
    tty: false
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m
  - name: "clientbase"
    image: "docker.repo.ercot.com/ercot/tools/openshift/client/base:latest"
    imagePullPolicy: "IfNotPresent"
    tty: true
    securityConext:
      privileged: true
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m
    volumeMounts:
    - name: "buildah-cache"
      mountPath: "/var/lib/container"
